export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_ACTIVE_INBOX = 'SET_ACTIVE_INBOX';
export const UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS';
export const UPDATE_UNREAD_COUNT = 'UPDATE_UNREAD_COUNT';
export const LOG_OUT = 'LOG_OUT';
